package com.example.manuel_sorg.networkscanner.Network;

import java.util.HashMap;

public class Ports {

    public static enum Port {
        reserviert(0),
        TCP_Port_Service_Multiplexer(1),
        CompressNET_Management_Utility(2),
        CompressNET_Compression_Process(3),
        Mesh_Connection_Protocol(4),
        Remote_Job_Entry(5),
        nicht_zugewiesen(6),
        Echo(7),
        Nicht_zugewiesen1(8),
        Discard(9),
        Nicht_zugewiesen2(10),
        Systeminformationen(11),
        LBBP(12),
        Daytime(13),
        Nicht_zugewiesen3(14),
        netstat_Service(15),
        Nicht_zugewiesen4(16),
        Quote_of_the_Day(17),
        Message_Send_Protocol(18),
        Character_Generator_Protocol(19),
        FTP_Datenuebertragung(20),
        FTP_Verbindungsaufbau(21),
        SSH(22),
        Telnet(23),
        LMTP(24),
        SMTP(25),
        Nicht_zugewiesen5(26),
        RF_Remote_File(34),
        Private_Druckserverprotokolle(35),
        TIME_Protokoll(37),
        RLP_Resource_Location_Protocol(39),
        Nicht_zugewiesen6(40),
        Grafiken(41),
        ARPA_Host_Name_Server_Protocol(42),
        WINS(42),
        Whois_Protokoll(43),
        NI_FTP(47),
        TACACS_Login_Host_Protocol(49),
        Remote_Mail_Checking_Protocol(50),
        IMP_Logical_Address_Maintenance(51),
        XNS_Xerox_Network_Systems_Time_Protocol(52),
        DNS(53),
        XNS_Clearinghouse(54),
        ISI_Graphics_Language(55),
        XNS_Authentication(56),
        Route_Access_Protocol(56),
        MTP(57),
        XNS_Mail(58),
        DHCP(67),
        DHCP2(68),
        TFTP(69),
        Gopher_Protokoll(70),
        Genius_Protokoll(71),
        Finger(79),
        HTTP(80),
        Torpark_Onion_Routing(81),
        Torpark_Control(82),
        MIT_ML_Device(83),
        Kerberos_Authentifizierungssystem(88),
        Pointcast(90),
        WIP_Message(99),
        NIC_host_name(101),
        TSAP(102),
        Digital_Imaging_and_Communications_in_Medicine(104),
        CCSO_Nameserver_Protocol(105),
        Remote_Telnet_Service_protocol(107),
        SNA_Gateway_Access_Server(108),
        POP2(109),
        POP3(110),
        ONC_(111),
        ident(113),
        SFTP(115),
        UUCP_Path_Service(117),
        SQL_Dienste(118),
        NNTP(119),
        Network_Time_Protocol(123),
        DCE_Endpunkt_Auflösung(135),
        Microsoft_EPMAP(135),
        NetBIOS_Name_Service(137),
        NetBIOS_Datagram_Service(138),
        NetBIOS_Session_Service(139),
        IMAP(143),
        Jargon_Server(148),
        Background_File_Transfer_Program(152),
        Simple_Gateway_Monitoring_Protocol(153),
        SQL_Service(156),
        DMSP_Distributed_Mail_Service_Protocol(158),
        Simple_Network_Management_Protocol(161),
        Simple_Network_Management_Protocol_Trap(162),
        Print_srv_Network_PostScript(170),
        X_Display_Manager_Control_Protocol(177),
        BGP(179),
        Internet_Relay_Chat(194),
        SNMP_Unix_Multiplexer(199),
        AppleTalk_Routing_Maintenance(201),
        Quick_Mail_Transfer_Protocol(209),
        ANSI(210),
        Internetwork_Packet_Exchange(213),
        Message_posting_protocol(218),
        Internet_Message_Access_Protocol(220),
        DEV_Port(256),
        Efficient_Short_Remote_Operations(259),
        Border_Gateway_Multicast_Protocol(264),
        Novastor_Online_Backup(308),
        Mac_OS_X_Server(311),
        PKIX_TSP_Time_Stamp_Protocol(318),
        Precision_Time_Protocol_Events(319),
        Precision_Time_Protocol_General_Messages(320),
        Internet_Message_Mapping_Protocol(323),
        IT_Message_Message_Event(325),
        IT_Message_Status_Control_Event(327),
        IT_Message_Gif_Event(330),
        MATIP(350),
        MATIP2(351),
        ODMR(366),
        Rpc2portmap(369),
        codaauth2_Coda_authentication_server(370),
        ClearCase_albd(371),
        HP_data_alarm_manager(383),
        Ein_Remote_Network_Server_System(384),
        AURP(387),
        Lightweight_Directory_Access_Protocol(389),
        UPS_Uninterruptible_Power_Supply(401),
        Altiris_Deployment_Client(402),
        Direct_Connect_Hub(411),
        Direct_Connect_Client_to_Client(412),
        Service_Location_Protocol(427),
        HTTPS(443),
        SNPP(444),
        Microsoft_DS_Active_Directory(445),
        Microsoft_DS_SMB(445),
        Kerberos_Change(464),
        URD(465),
        SMTP_over_SSL(465),
        tcpnethaspsrv(475),
        Dantz_Retrospect(497),
        Internet_Security_Association_and_Key_Management_Protocol(500),
        STMF(501),
        Modbus_Protocol(502),
        Multidienst_Protokoll_für_das_Citadel_Groupware_Protokoll(504),
        First_Class_Protocol(510),
        Remote_Process_Execution(512),
        rlogin(513),
        Syslog_für_System_Logs(514),
        Line_Printer_Daemon_Druckservices(515),
        Talk(517),
        NTalk(518),
        efs_extended_file_name_server(520),
        NCP(524),
        Timed_ein_Zeitserver(525),
        Courier(530),
        AOL_Instant_Messenger_IRC(531),
        netnews(532),
        netwall(533),
        UUCP(540),
        Kerberos_login(543),
        Kerberos_Remote_shell(544),
        OSISoft_PI_Server_Client_Access(545),
        DHCPv6_Client(546),
        DHCPv6_Server(547),
        Apple_Filing_Protocol(548),
        new_rwho_new_who(550),
        Real_Time_Streaming_Protocol(554),
        RFS_Server(556),
        Remote_Monitor(560),
        monitor(561),
        NNTPS(563),
        SMTP2(587),
        FileMaker6(591),
        HTTP_RPC_Ep_Map(593),
        Reliable_Event_Logging_Protocol(601),
        TUNNEL_profile(604),
        ASF_RMCP(623),
        MSA_Minecraft_Server_Administrator(628),
        Internet_Printing_Protocol_IPP(631),
        RLZ_DBase(635),
        Lightweight_Directory_Access_Protocol2(636),
        MSDP_Multicast_Source_Discovery_Protocol(639),
        SupportSoft_Nexus_Remote_Command(641),
        LDP_Label_Distribution_Protocol(646),
        DHCP_Failover_protocol(647),
        RRP_Registry_Registrar_Protocol(648),
        IEEE_MMS(651),
        DTCP(652),
        SupportSoft_Nexus_Remote_Command2(653),
        Media_Management_System_MMS_Media_Management_Protocol_MMP(654),
        VPN_Virtual_Private_Network(655),
        IBM_RMC(657),
        Mac_OS_X_Server_Administration(660),
        sun_dr_Remote_Dynamic_Reconfiguration(665),
        Doom_erster_online_First_Person_Shooter(666),
        ACAP_Application_Configuration_Access_Protocol(674),
        MS_Exchange_Routing(691),
        Hyperwave_ISP(692),
        Linux_HA_High_availability_Heartbeat(694),
        IEEE_MMS_SSL(695),
        OLSR_Optimized_Link_State_Routing(698),
        Access_Network(699),
        EPP_Extensible_Provisioning_Protocol(700),
        LMP_Link_Management_Protocol(701),
        IRIS_Internet_Registry_Information_Service(702),
        Secure_Internet_Live_Conferencing(706),
        Cisco_Tag_Distribution_Protocol(711),
        Promise_RAID_Controller(712),
        SMQP_Simple_Message_Queue_Protocol(720),
        Kerberos_administration(749),
        Kerberos_version_IV(750),
        pump(751),
        qrh(752),
        Reverse_Routing_Header(753),
        krb5_prop_Kerberos_v5_slave_propagation(754),
        krbupdate_Kerberos_registration(760),
        Conserver_serial_console_management_server(782),
        SpamAssassin_spamd_daemon(783),
        CMP_Certificate_Management_Protocol(829),
        Adobe_Flash_socket_policy_server(843),
        DHCP_Failover_protocol2(847),
        DNS_over_TLS(853),
        iSCSI_(860),
        rsync_Datei_Synchronisationsprotokoll(873),
        cddbp_CD_DataBase_protocol(888),
        VMware_Virtual_Infrastructure_Client(901),
        VMware_Server_Console(902),
        VMware_Remote_Console(903),
        VMware_Server_Alternate(904),
        Network_Console_on_Acid(911),
        Domain_Name_System(953),
        SofaWare_Technologies_Remote(981),
        externer_SSL_Zugriff(987),
        FTPS_Protocol(989),
        FTPS_Protocol2(990),
        NAS_Netnews_Administration_System(991),
        TELNET_protocol_over_TLS_SSL(992),
        Internet_Message_Access_Protocol_over_TLS_SSL(993),
        POP3S(995),
        ScimoreDB_Database_System(999),
        JtoMB(1001),
        Opsware_agent(1002),
        Reserviert(1023),
        Session_Initiation_Protocol(5060);

        private static final String TAG = "Ports";

        private static HashMap<Integer, Port> portsByNumber;

        static {
            portsByNumber = new HashMap<Integer, Port>();
            for (Port port : Port.values()) {
                portsByNumber.put(port.getPort(), port);
            }
        }

        int port;

        Port(int port) {
            this.port = port;
        }

        public int getPort() {
            return port;
        }

        public static Port getForPort(int port) {
            return portsByNumber.get(port);
        }
    }
}
